### ISSUE TITLE
Health Effects section doesn't make sense

### ISSUE THREAD

**Issue by M-Davies** [dambem/ClimateMonitorV2#47]
## Description
<img width="983" alt="Screenshot 2020-06-21 at 13 30 15" src="https://user-images.githubusercontent.com/25231953/85224602-5be5c180-b3c3-11ea-9194-5dface2e0c33.png">
I don't really understand the point of this section. What is it supposed to represent? Why is the information repeated twice? I believe this section could be touched up a little bit to fully explain this (hence the Design Improvement label)

**Comment by dambem** [comment]
So this section has been touched up in a newer branch of mapping, which im gonna get merged in today. It's still needing some design improvements but essentially the point of it is to show based on the current levels, what would the actual health effects be,in order to try and make the oftentimes unpersonal data a little bit more real to somebody. 
![image](https://user-images.githubusercontent.com/18164343/85224841-014d6500-b3c5-11ea-8ea6-d8558ff0408b.png)

**Comment by M-Davies** [comment]
Closed by https://github.com/dambem/ClimateMonitorV2/pull/49
