### ISSUE TITLE
Weather Information Using Weather Company

### ISSUE THREAD

**Issue by dambem** [dambem/ClimateMonitorV2#9]
PM10 and PM2.5 are incredibly dependent on weather conditions, integration with current weather in an area could be quite interesting

**Comment by M-Davies** [comment]
Forwarding on the information in https://trello.com/c/qQvKH7JL/38-useful-apis, I believe there's a couple of API's that could help us here:
- One being the Weather company bluemix API (https://twcservice.mybluemix.net/rest-api/#). This API seems to be the official weather company api but I can't get a response from it using a https query due to it being a bluemix only API (i think, I was reading through [this documentation](https://cloud.ibm.com/docs/services/Weather?topic=weather-insights_weather_overview) and that seems to be the case). I'm still looking for a non-bluemix weather company API but I'm doubtful I'll find one as it looks like [IBM has privatised it](https://www.ibm.com/uk-en/marketplace/weather-company-data-packages). We would either need to create a bluemix application that pulls in the data from our API and forwards it to our python scripts OR cough up and pay for the web one
- There is also ye old'e Breezeometer (https://breezometer.com/air-quality-map/city/sheffield?lat=53.3825&lon=-1.47194). Their [pricing plans](https://breezometer.com/plans) are difficult to deal with as we would need to get the Enterprise version for everything we need, including historical data. However, the information they have is [pretty powerful](https://docs.breezometer.com/api-documentation/air-quality-api/v2/#customized-request) and seems like it would be all we need.
- There is also a whole bunch of free API's here that we could utilise too https://rapidapi.com/blog/access-global-weather-data-with-these-weather-apis/. Specifically, I've been looking at https://rapidapi.com/darkskyapis/api/dark-sky/pricing and the pricing seems reasonable for what it is. 
<img width="988" alt="Screenshot 2020-05-17 at 16 22 16" src="https://user-images.githubusercontent.com/25231953/82152655-b8047580-985a-11ea-93ca-2413ce4b1d3c.png">

@dambem Thoughts?

**Comment by dambem** [comment]
Just saw this! @Megan-Wright  has some more details for the different API stuff, but with the weather company data we actually already have some of these!

**Comment by M-Davies** [comment]
Yeah this was commented ages ago so most of the info I put above is likely out of date at this point

**Comment by M-Davies** [comment]
Implemented by https://github.com/dambem/ClimateMonitorV2/pull/70 (Hats off to @Megan-Wright )
